{
 "title": "Nibiru Oracle Dashboard",
 "tags": [
  "blockchain",
  "nibiru"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(miss_counter, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sum of Miss Pairs Over Time (5m)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum_over_time(aggregated_votes{instance=\"$instance\"}[5m])",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Miss Counter Stats (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "delta(miss_counter{instance=\"$instance\"}[5m])",
     "legendFormat": "{{valoper}}"
    }
   ]
  },
  {
   "title": "Miss Rate Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "miss_rate{instance=\"$instance\"} * 100",
     "legendFormat": "{{valoper}}"
    }
   ]
  },
  {
   "title": "Oracle Configuration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slash_window{instance=\"$instance\"}",
     "legendFormat": "slash window"
    },
    {
     "expr": "vote_period{instance=\"$instance\"}",
     "legendFormat": "vote period"
    },
    {
     "expr": "window_size{instance=\"$instance\"}",
     "legendFormat": "window size"
    },
    {
     "expr": "min_valid_per_window{instance=\"$instance\"}",
     "legendFormat": "minimum valid per window"
    },
    {
     "expr": "slash_fraction{instance=\"$instance\"}",
     "legendFormat": "slash fraction"
    },
    {
     "expr": "symbols_count{instance=\"$instance\"}",
     "legendFormat": "pairs count"
    }
   ]
  },
  {
   "title": "Window Progress",
   "type": "stat",
   "description": "current slash window progress, block number in the current window",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "window_progress{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Window Progress",
   "type": "stat",
   "description": "Percentage completion of current window",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "window_progress{instance=\"$instance\"} / window_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Windows Start",
   "type": "stat",
   "description": "Next estimated new windows start",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "next_window_start{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Miss Counter",
   "type": "stat",
   "description": "number of block vote was missed",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miss_counter{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Miss Rate",
   "type": "stat",
   "description": "should not exceed 95% as it will lead to validator slash",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miss_rate{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Block Vote",
   "type": "stat",
   "description": "should go up by 5 every 30s",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_block_vote{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}